#!/bin/bash
# Generates RAUC bundle-signing cert/key material, in one of two modes:
#
#   ./generate-rauc-cert.sh dev [output-dir]
#       A single throwaway self-signed cert/key pair. Fine for exercising
#       the build/bundle/sign pipeline end-to-end. NOT for a real fleet —
#       one flat key signs bundles AND is the device's entire root of
#       trust, so there's no way to rotate/revoke it without re-flashing
#       every device's keyring.
#
#   ./generate-rauc-cert.sh production [output-dir]
#       A small CA hierarchy: an offline root CA (rarely touched, backed
#       up securely, never used to sign a bundle directly) plus a signing
#       cert/key issued *by* that CA (the one CI actually uses day to day).
#       Devices trust the CA — so the signing cert/key can be rotated or
#       revoked later without ever touching a device in the field. This is
#       the standard pattern RAUC's own documentation recommends; see
#       https://rauc.readthedocs.io/en/latest/examples.html#creating-certificates
#       and cross-check it against whatever RAUC version you're actually
#       deploying before trusting a fleet to it.
#
# Either mode writes a MANIFEST.txt into output-dir explaining what every
# generated file is for and how sensitive it is — read it before you decide
# where any of this ends up, and read it again before you delete this
# terminal's scrollback.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODE="${1:-}"

usage() {
	cat >&2 <<EOF
usage: $0 dev [output-dir]
       $0 production [output-dir]
EOF
	exit 1
}

[ "$MODE" = "dev" ] || [ "$MODE" = "production" ] || usage
OUT_DIR="${2:-${HERE}/certs}"

if [ -e "$OUT_DIR" ] && [ -n "$(ls -A "$OUT_DIR" 2>/dev/null)" ]; then
	echo "generate-rauc-cert.sh: ${OUT_DIR} already exists and isn't empty — remove/rename it first, or pass a different output-dir" >&2
	exit 1
fi
mkdir -p "$OUT_DIR"
chmod 700 "$OUT_DIR"

# ---------------------------------------------------------------------------
if [ "$MODE" = "dev" ]; then

KEY="${OUT_DIR}/dev-key.pem"
CERT="${OUT_DIR}/dev-cert.pem"

openssl req -x509 -newkey rsa:4096 -nodes -days 3650 \
	-keyout "$KEY" -out "$CERT" \
	-subj "/CN=Slide Announcer Dev RAUC Signing Cert" 2>/dev/null
chmod 600 "$KEY"
chmod 644 "$CERT"

cat > "${OUT_DIR}/MANIFEST.txt" <<EOF
Slide Announcer — dev/test RAUC cert (generated by generate-rauc-cert.sh dev)
Not for a real fleet. See generate-rauc-cert.sh's own header comment.

dev-key.pem   (600, PRIVATE) — signs bundles. Anyone with this can sign a
              bundle every device with dev-cert.pem in its keyring will
              accept. Keep off shared machines; fine to regenerate/discard
              freely since nothing production depends on it.
dev-cert.pem  (644, public)  — baked into the device keyring AND used to
              sign bundles (single-cert setup — see the production mode
              for why a real fleet wants these to be two different certs).
EOF

cat <<EOF

Generated a DEV-ONLY RAUC signing cert/key pair in ${OUT_DIR}:
  cert: ${CERT}
  key:  ${KEY}

Now copy image-builder/.env.example to image-builder/.env and set:
  RAUC_CERT_PATH=${CERT}
  RAUC_KEY_PATH=${KEY}
(leave RAUC_KEYRING_CERT_PATH unset — it defaults to RAUC_CERT_PATH)

This is a self-signed, dev-only cert — good for testing the bundle/OTA
pipeline end-to-end, not for a real fleet. Run '$0 production' instead
for that.
EOF

# ---------------------------------------------------------------------------
else # production

echo "== Slide Announcer RAUC production PKI setup =="
echo
echo "This creates an offline root CA plus a day-to-day signing cert issued"
echo "by it. You'll be asked for a passphrase to encrypt the CA private key"
echo "(mandatory — this key is the fleet's entire root of trust and should"
echo "essentially never be typed into a running CI job) and the identifying"
echo "details below (defaults shown; press enter to accept)."
echo

read -r -p "CA common name [Slide Announcer Fleet Root CA]: " CA_CN
CA_CN="${CA_CN:-Slide Announcer Fleet Root CA}"
read -r -p "CA validity in days [7300 (~20 years)]: " CA_DAYS
CA_DAYS="${CA_DAYS:-7300}"
read -r -p "Signing cert common name [Slide Announcer OTA Signing $(date -u +%Y 2>/dev/null || echo cert)]: " SIGN_CN
SIGN_CN="${SIGN_CN:-Slide Announcer OTA Signing}"
read -r -p "Signing cert validity in days [730 (~2 years)]: " SIGN_DAYS
SIGN_DAYS="${SIGN_DAYS:-730}"

CA_KEY="${OUT_DIR}/ca-key.pem"
CA_CERT="${OUT_DIR}/ca-cert.pem"
SIGN_KEY="${OUT_DIR}/signing-key.pem"
SIGN_CERT="${OUT_DIR}/signing-cert.pem"
SIGN_CHAIN="${OUT_DIR}/signing-cert-chain.pem"
SIGN_CSR="$(mktemp)"
trap 'rm -f "$SIGN_CSR"' EXIT

echo
echo "== Generating CA key — you'll be prompted for an encryption passphrase now =="
echo "   (write this passphrase down somewhere as secure as the key itself —"
echo "    an encrypted key with a lost passphrase is as good as no key at all)"
openssl genrsa -aes256 -out "$CA_KEY" 4096
chmod 600 "$CA_KEY"

echo
echo "== Self-signing the CA certificate =="
openssl req -x509 -new -key "$CA_KEY" -sha256 -days "$CA_DAYS" \
	-subj "/CN=${CA_CN}" -out "$CA_CERT"
chmod 644 "$CA_CERT"

echo
echo "== Generating the signing key + CSR =="
# Deliberately unencrypted: this is the key CI signs bundles with on every
# build, and RAUC's own signing invocation has no interactive passphrase
# prompt story that fits an automated pipeline. It's protected instead by
# being scoped, rotatable, and revocable (that's the entire point of
# having a CA at all) — keep it in a CI secret store, not on disk on a
# shared build box.
openssl genrsa -out "$SIGN_KEY" 4096
chmod 600 "$SIGN_KEY"
openssl req -new -key "$SIGN_KEY" -sha256 -subj "/CN=${SIGN_CN}" -out "$SIGN_CSR"

echo
echo "== Signing the signing-cert with the CA — re-enter the CA key passphrase =="
openssl x509 -req -in "$SIGN_CSR" -CA "$CA_CERT" -CAkey "$CA_KEY" -CAcreateserial \
	-days "$SIGN_DAYS" -sha256 -out "$SIGN_CERT"
chmod 644 "$SIGN_CERT"
rm -f "${OUT_DIR}/ca-cert.srl"

# RAUC's --cert accepts the leaf cert followed by its issuing chain in one
# file (leaf first) — this is what a device only holding the CA cert in
# its keyring needs in order to verify a bundle signed by this leaf.
cat "$SIGN_CERT" "$CA_CERT" > "$SIGN_CHAIN"
chmod 644 "$SIGN_CHAIN"

sha256sum "$CA_KEY" "$CA_CERT" "$SIGN_KEY" "$SIGN_CERT" "$SIGN_CHAIN" \
	> "${OUT_DIR}/SHA256SUMS.txt"

cat > "${OUT_DIR}/MANIFEST.txt" <<EOF
Slide Announcer — production RAUC PKI (generated by generate-rauc-cert.sh production)
Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo unknown)
CA CN: ${CA_CN} (${CA_DAYS} days)
Signing CN: ${SIGN_CN} (${SIGN_DAYS} days)

WHAT TO BACK UP, AND HOW SECURELY
==================================

ca-key.pem  (600, PRIVATE, passphrase-encrypted)
    The fleet's entire root of trust. Anyone holding this AND its
    passphrase can mint a new signing cert every device in the fleet will
    trust forever (until CA_DAYS expires). This should leave this machine
    for offline storage immediately — encrypted backup media, a hardware
    security module, or at minimum a password manager's most restricted
    vault — and should NOT live on any CI runner or build host long-term.
    Losing it (with no other copy) means you can never rotate the signing
    cert again without re-flashing every device's keyring with a new CA.
    Its passphrase must be backed up separately from the key file itself
    (never in the same place) — write it down, or store it in a distinct
    secrets vault from wherever the key file itself is kept.

ca-cert.pem  (644, public, NOT secret)
    Goes into every device's keyring at image-build time
    (RAUC_KEYRING_CERT_PATH). Losing the *file* is recoverable (it's
    derivable from ca-key.pem), but you still need a copy of it on hand
    for every future image build, so keep it wherever your build
    configuration/secrets for this project already live.

signing-key.pem  (600, PRIVATE, NOT encrypted)
    What CI actually signs bundles with (RAUC_KEY_PATH), day to day. Store
    it in your CI/CD secret store (GitHub Actions secrets, a vault, etc.),
    not as a plain file on a shared machine. If this leaks, revoke/replace
    it — see "If a key leaks," below — but a leak here does NOT compromise
    ca-key.pem or force a fleet re-flash.

signing-cert.pem  (644, public, NOT secret)
    The signing cert on its own — kept for reference/re-chaining later;
    the bundle-signing step actually uses signing-cert-chain.pem below.

signing-cert-chain.pem  (644, public, NOT secret)
    signing-cert.pem + ca-cert.pem concatenated (leaf first) — this is
    RAUC_CERT_PATH. RAUC embeds this chain in each bundle's signature so a
    device holding only ca-cert.pem in its keyring can still verify a
    bundle signed by this leaf cert.

SHA256SUMS.txt
    Checksums of every file above, generated at the same time — compare
    against this after moving files to backup media, to confirm nothing
    got truncated/corrupted in transit.

.env FOR THIS SETUP
====================
RAUC_CERT_PATH=${SIGN_CHAIN}
RAUC_KEY_PATH=${SIGN_KEY}
RAUC_KEYRING_CERT_PATH=${CA_CERT}

IF A KEY LEAKS
==============
- signing-key.pem leaks: reissue a new signing cert from the same CA
  (re-run this script's CA-signing step against a fresh key/CSR — a
  future revision of this script may add a dedicated "reissue" mode; for
  now, mirror the openssl invocations above by hand) and roll it out via
  a normal build — no device touch needed, since they all still trust the
  same CA. Consider RAUC's CRL support if you need to actively block the
  old cert before it expires on its own, rather than just letting it lapse.
- ca-key.pem leaks: there is no clean recovery — every device's baked-in
  root of trust is compromised. This means generating a new CA and
  shipping an OS update that replaces /etc/rauc/keyring.pem fleet-wide
  before you can trust the signing pipeline again.
EOF
chmod 600 "${OUT_DIR}/MANIFEST.txt"

cat <<EOF

Generated a production RAUC PKI in ${OUT_DIR}:
  CA cert:            ${CA_CERT}   (public — bake into every image's keyring)
  CA key:             ${CA_KEY}   (PRIVATE — move to offline/secure storage now)
  signing cert chain: ${SIGN_CHAIN}   (public — RAUC_CERT_PATH)
  signing key:        ${SIGN_KEY}   (PRIVATE — RAUC_KEY_PATH, belongs in a CI secret store)

Full explanation of every file, its sensitivity, and backup guidance is in
${OUT_DIR}/MANIFEST.txt — read it now, before this terminal's scrollback
is your only other copy.

Now copy image-builder/.env.example to image-builder/.env and set:
  RAUC_CERT_PATH=${SIGN_CHAIN}
  RAUC_KEY_PATH=${SIGN_KEY}
  RAUC_KEYRING_CERT_PATH=${CA_CERT}
EOF

fi
